# 应用服务 WEB 访问端口
server:
  port: 8080
#下面这些内容是为了让MyBatis映射

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.snail.mybatis.entity
--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rmsdb3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin